### ISSUE TITLE
Build in service worker component 

### ISSUE THREAD

**Issue by tanyagupta** [gwg-women/gwg-women-techmakers#1]
Cache the first search results, skeleton, css and other elements

Added 2/18
store static map - see [Google Static Maps](https://developers.google.com/maps/documentation/static-maps/intro) and store the static map
Store css
Store html

By 3/4

**Comment by tanyagupta** [comment]
Would anyone like to take this on? If so please unassign others and assign yourself

**Comment by digilou** [comment]
@tanyagupta I'll give it a go! If I don't get it in the next few days, I'll unassign myself and give someone else a shot.

**Comment by digilou** [comment]
Waiting for packages in issue #4 before proceeding.

**Comment by digilou** [comment]
#29 closed this. We can revisit when other components have been created and refactoring happens. It will have to be tested often.

**Comment by tanyagupta** [comment]
Thanks again @digilou. I will open a new issue to generate and then store a static map

**Comment by amr08** [comment]
I am seeing the files store after registration, but I'm getting undefined for fetch in the sw file and no content is getting delivered yet.   I'm currently trying to debug, but thought it would be good to open up for others to look at as well.  I'll untag myself from the static map for now because I'm thinking we should probably get some (any) offline functionality solved first.
